package net.phoenix_tesla_network.tesla.common.machine;

import com.gregtechceu.gtceu.api.data.chemical.ChemicalHelper;
import com.gregtechceu.gtceu.api.data.tag.TagPrefix;
import com.gregtechceu.gtceu.api.machine.MultiblockMachineDefinition;
import com.gregtechceu.gtceu.api.pattern.BlockPattern;
import com.gregtechceu.gtceu.api.pattern.FactoryBlockPattern;
import com.gregtechceu.gtceu.api.pattern.Predicates;
import com.gregtechceu.gtceu.common.data.GCYMBlocks;
import com.gregtechceu.gtceu.common.data.GTBlocks;

import net.minecraft.world.item.DyeColor;
import net.phoenix_tesla_network.tesla.api.pattern.PhoenixPredicates;
import net.phoenix_tesla_network.tesla.common.block.PhoenixTeslaBlocks;
import net.phoenix_tesla_network.tesla.common.data.materials.PhoenixProgressionMaterials;
import net.phoenix_tesla_network.tesla.configs.PhoenixTeslaConfigs;

import static com.gregtechceu.gtceu.api.pattern.Predicates.blocks;
import static com.gregtechceu.gtceu.api.pattern.Predicates.controller;

/**
 * The Basic (11 x 11 x 28) and Advanced (19 x 19 x 53) Tesla Tower structures. The Ultimate tower keeps its own
 * pattern in {@link PhoenixTeslaMachines}. Hatches may replace the tower's own tier casing, exactly as they do on the
 * Ultimate tower.
 */
final class TowerPatterns {

    private TowerPatterns() {}

    /** Basic: the small tower. Hatches go on the Insanely Supercharged Tesla casing ("C"). */
    static BlockPattern basic(MultiblockMachineDefinition definition, PhoenixTeslaConfigs.TowerProfile profile) {
        return FactoryBlockPattern.start()
                .aisle("AABBBBBBBAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AACCCCCCCAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("ABBCCCCCBBA", "AAAAECEAAAA", "AAAAECEAAAA", "AAACCCCCAAA", "AAAFFCFFAAA", "AAAFFCFFAAA",
                        "AAAFFCFFAAA", "ACCGGCGGCCA", "AAAEAAAEAAA", "AAAEAAAEAAA", "AAAGGGGGAAA", "AAAFFFFFAAA",
                        "AAAFFFFFAAA", "AAAGGGGGAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("BBCCGGGCCBB", "AAAAAAAAAAA", "AAAAAAAAAAA", "AACCGGGCCAA", "AAGFAAAFGAA", "AAGFAAAFGAA",
                        "AAGFAAAFGAA", "CCGGHCHGGCC", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAGGBBBGGAA", "AAFFAAAFFAA",
                        "AAFFAAAFFAA", "AAGGBBBGGAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAABBBBBAAA", "AAACFFFCAAA",
                        "AAACFFFCAAA", "AAACFFFCAAA", "AAACCCCCAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("BCCGGHGGCCB", "AAAAAAAAAAA", "AAAAAAAAAAA", "ACCGGHGGCCA", "AFFAAAAAFFA", "AFFAAAAAFFA",
                        "AFFAAAAAFFA", "CGGHHCHHGGC", "AEAAAAAAAEA", "AEAAAAAAAEA", "AGGBBHBBGGA", "AFFAAAAAFFA",
                        "AFFAAAAAFFA", "AGGBBBBBGGA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AABBHHHBBAA", "AACHAAAHCAA",
                        "AACHAAAHCAA", "AACHAAAHCAA", "AACCBBBCCAA", "AAAACCCAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("BCGGHHHGGCB", "AEAAAIAAAEA", "AEAAAAAAAEA", "ACGGHHHGGCA", "AFAAAAAAAFA", "AFAAAAAAAFA",
                        "AFAAAAAAAFA", "CGHHHCHHHGC", "AAAAJEJAAAA", "AAAAJEJAAAA", "AGBBHEHBBGA", "AFAAAEAAAFA",
                        "AFAAAEAAAFA", "AGBBBEBBBGA", "AAAAHEHAAAA", "AAAAHEHAAAA", "AABHHEHHBAA", "AAFAAEAAFAA",
                        "AAFAAEAAFAA", "AAFAAEAAFAA", "AACBBEBBCAA", "AAACCECCAAA", "AAAACECAAAA", "AAAACECAAAA",
                        "AAAACECAAAA", "AAAACCCAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("BCGHHHHHGCB", "ACAAIEIAACA", "ACAAAKAAACA", "ACGHHEHHGCA", "ACAAAEAAACA", "ACAAAEAAACA",
                        "ACAAAEAAACA", "CCCCCCCCCCC", "AAAAELEAAAA", "AAAAELEAAAA", "AGBHELEHBGA", "AFAAELEAAFA",
                        "AFAAELEAAFA", "AGBBELEBBGA", "AAAAELEAAAA", "AAAAELEAAAA", "AABHELEHBAA", "AAFAELEAFAA",
                        "AAFAELEAFAA", "AAFAELEAFAA", "AACBELEBCAA", "AAACELECAAA", "AAAAELEAAAA", "AAAAELEAAAA",
                        "AAAAELEAAAA", "AAAACLCAAAA", "AAAAALAAAAA", "AAAAALAAAAA")
                .aisle("BCGGHHHGGCB", "AEAAAIAAAEA", "AEAAAAAAAEA", "ACGGHHHGGCA", "AFAAAAAAAFA", "AFAAAAAAAFA",
                        "AFAAAAAAAFA", "CGHHHCHHHGC", "AAAAJEJAAAA", "AAAAJEJAAAA", "AGBBAEHBBGA", "AFAAAEAAAFA",
                        "AFAAAEAAAFA", "AGBBBEBBBGA", "AAAAHEHAAAA", "AAAAHEHAAAA", "AABHHEHHBAA", "AAFAAEAAFAA",
                        "AAFAAEAAFAA", "AAFAAEAAFAA", "AACBBEBBCAA", "AAACCECCAAA", "AAAACECAAAA", "AAAACECAAAA",
                        "AAAACECAAAA", "AAAACCCAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("BCCGGHGGCCB", "AAAAAAAAAAA", "AAAAAAAAAAA", "ACCGGHGGCCA", "AFFAAAAAFFA", "AFFAAAAAFFA",
                        "AFFAAAAAFFA", "CGGHHCHHGGC", "AEAAAAAAAEA", "AEAAAAAAAEA", "AGGBBHBBGGA", "AFFAAAAAFFA",
                        "AFFAAAAAFFA", "AGGBBBBBGGA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AABBHHHBBAA", "AACHAAAHCAA",
                        "AACHAAAHCAA", "AACHAAAHCAA", "AACCBBBCCAA", "AAAACCCAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("BBCCGGGCCBB", "AAAAAAAAAAA", "AAAAAAAAAAA", "AACCGGGCCAA", "AAGFAAAFGAA", "AAGFAAAFGAA",
                        "AAGFAAAFGAA", "CCGGHCHGGCC", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAGGBBBGGAA", "AAFFAAAFFAA",
                        "AAFFAAAFFAA", "AAGGBBBGGAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAABBBBBAAA", "AAACFFFCAAA",
                        "AAACFFFCAAA", "AAACFFFCAAA", "AAACCCCCAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("ABBCCCCCBBA", "AAAAEMEAAAA", "AAAAECEAAAA", "AAACCCCCAAA", "AAAFFCFFAAA", "AAAFFCFFAAA",
                        "AAAFFCFFAAA", "ACCGGCGGCCA", "AAAEAAAEAAA", "AAAEAAAEAAA", "AAAGGGGGAAA", "AAAFFFFFAAA",
                        "AAAFFFFFAAA", "AAAGGGGGAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .aisle("AABBBBBBBAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AACCCCCCCAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA",
                        "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA", "AAAAAAAAAAA")
                .where("A", Predicates.any())
                .where("B", blocks(PhoenixTeslaBlocks.SOURCE_FIBER_MACHINE_CASING.get()))
                .where("C", PhoenixTeslaMachines.hatchPredicate(definition, profile,
                        PhoenixTeslaBlocks.INSANELY_SUPERCHARGED_TESLA_CASING.get()))
                .where("E", blocks(ChemicalHelper.getBlock(TagPrefix.frameGt,
                        PhoenixProgressionMaterials.RESONANT_RHODIUM_ALLOY)))
                .where("F", blocks(GTBlocks.CASING_LAMINATED_GLASS.get())
                        .or(blocks(GTBlocks.FUSION_GLASS.get())))
                .where("G", Predicates.blocks(PhoenixTeslaBlocks.MACHINE_CASING_RHODIUM_PLATED_PALLADIUM.get()))
                .where("H", Predicates.lampsByColor(DyeColor.PURPLE))
                .where("I", blocks(PhoenixTeslaBlocks.MACHINE_CASING_NAQUADAH_ALLOY.get()))
                .where("J", blocks(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING.get()))
                .where("K", PhoenixPredicates.teslaBatteries(profile.minBatteryTier, profile.maxBatteryTier))
                .where("L", blocks(GTBlocks.COIL_CUPRONICKEL.get()))
                .where("M", controller(blocks(definition.get())))
                .build();
    }

    /** Advanced: the large tower with the advanced casings. Hatches go on the Advanced Tesla casing ("J"). */
    static BlockPattern advanced(MultiblockMachineDefinition definition, PhoenixTeslaConfigs.TowerProfile profile) {
        return FactoryBlockPattern.start()
                .aisle("AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAABBBBBAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA",
                        "AAAAAAABBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAABBBEFEBBBAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA",
                        "AAAAABBBHFHBBBAAAAA", "AAAAAAAFAAAFAAAAAAA", "AAAAAAAFAAAFAAAAAAA", "AAAAAAAFAAAFAAAAAAA",
                        "AAAAAAAFAAAFAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA",
                        "AAAAAAACCBCCAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAIIIIIIIIIAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAABBEEEFEEEBBAAAA", "AAAACCAAAAAAACCAAAA", "AAAACCAAAAAAACCAAAA", "AAAACCAAAAAAACCAAAA",
                        "AAAABBHHJFJHHBBAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAABBBEFEBBBAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA",
                        "AAAAAGCCAAACCGAAAAA", "AAAAABBBHFHBBBAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAIIJJJJJJJIIAAAA", "AAAAAAAAFJFAAAAAAAA", "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAFJFAAAAAAAA",
                        "AAABBEEGJJJGEEBBAAA", "AAAGCAAAAAAAAACGAAA", "AAAGCAAAAAAAAACGAAA", "AAAGCAAAAAAAAACGAAA",
                        "AAABBHHJIFIJHHBBAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAABBEEEFEEEBBAAAA", "AAAACCAAAAAAACCAAAA", "AAAACCAAAAAAACCAAAA",
                        "AAAACCAAAAAAACCAAAA", "AAAABBHHJFJHHBBAAAA", "AAAAAAAFAAAFAAAAAAA", "AAAAAAAFAAAFAAAAAAA",
                        "AAAAAAAFAAAFAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA",
                        "AAAAAAACCBCCAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAIIJJBBBBBJJIIAAA", "AAAAAJAAAAAAAJAAAAA", "AAAAAJAAAAAAAJAAAAA", "AAAAAJAAAAAAAJAAAAA",
                        "AABBEJGGJBJGGJEBBAA", "AACCAAAAAAAAAAACCAA", "AACCAAAAAAAAAAACCAA", "AACCAAAAAAAAAAACCAA",
                        "AABBHHJIIFIIJHHBBAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAABBEEIIIIIEEBBAAA", "AAACCAAAAAAAAACCAAA", "AAACCAAAAAAAAACCAAA",
                        "AAACCAAAAAAAAACCAAA", "AAABBHHJJFJJHHBBAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAABBBEFEBBBAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA",
                        "AAAAAGCCAAACCGAAAAA", "AAAAABBBJFJBBBAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIIJJBBBBBBBJJIIAA", "AAAAJAAAAAAAAAJAAAA", "AAAAJAAAAAAAAAJAAAA", "AAAAJAAAAAAAAAJAAAA",
                        "ABBEJGGJJBJJGGJEBBA", "AGCAAAAAAAAAAAAACGA", "AGCAAAAAAAAAAAAACGA", "AGCAAAAAAAAAAAAACGA",
                        "ABBHHJIIJJJIIJHHBBA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAABAAAAAAAAA", "AABBEEIIJBJIIEEBBAA", "AAGCAAAAAAAAAAACGAA", "AAGCAAAAAAAAAAACGAA",
                        "AAGCAAAAAAAAAAACGAA", "AABBHHJEEEEEJHHBBAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAABAAAAAAAAA", "AAAABBEEEFEEEBBAAAA", "AAAAGCAAAAAAACGAAAA", "AAAAGCAAAAAAACGAAAA",
                        "AAAAGCAAAAAAACGAAAA", "AAAABBJJIFIJJBBAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIJJBBBGGGBBBJJIAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "ABEEGGJJBBBJJGGEEBA", "ACAAAAAAAAAAAAAAACA", "ACAAAAAAAAAAAAAAACA", "ACAAAAAAAAAAAAAAACA",
                        "ABHHJIIBBGBBIIJHHBA", "AAAAAAAAKAKAAAAAAAA", "AAAAAAAAKAKAAAAAAAA", "AAAAAAAAKAKAAAAAAAA",
                        "AAAAAAAALBLAAAAAAAA", "AABEEIIJBBBJIIEEBAA", "AACAAAAAAAAAAAAACAA", "AACAAAAAAAAAAAAACAA",
                        "AACAAAAAAAAAAAAACAA", "AABHHJIIBBBIIJHHBAA", "AAAAAAAAKAKAAAAAAAA", "AAAAAAAAKAKAAAAAAAA",
                        "AAAAAAAALBLAAAAAAAA", "AAAABEEJJJJJEEBAAAA", "AAAACAAAAAAAAACAAAA", "AAAACAAAAAAAAACAAAA",
                        "AAAACAAAAAAAAACAAAA", "AAAABJJIBFBIJJBAAAA", "AAAAAAAAIAIAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIJBBBGGEGGBBBJIAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "BBEGGJJJBEBJJJGGEBB", "CCAAAAAAAAAAAAAAACC", "CCAAAAAAAAAAAAAAACC", "CCAAAAAAAAAAAAAAACC",
                        "BBHJIIBEEGEEBIIJHBB", "AFAAAAACAAACAAAAAFA", "AFAAAAACAAACAAAAAFA", "AFAAAAACAAACAAAAAFA",
                        "AFAAAAAILBLIAAAAAFA", "ABBEIIJJBEBJJIIEBBA", "ACCAAAAAAAAAAAAACCA", "ACCAAAAAAAAAAAAACCA",
                        "ACCAAAAAAAAAAAAACCA", "ABBHJEIBJJJBIEJHBBA", "AAAFAAACAAACAAAFAAA", "AAAFAAACAAACAAAFAAA",
                        "AAAFAAAILBLIAAAFAAA", "AAABBEJJIIIJJEBBAAA", "AAACCAAAAAAAAACCAAA", "AAACCAAAAAAAAACCAAA",
                        "AAACCAAAAAAAAACCAAA", "AAABBJIBBBBBIJBBAAA", "AAAAAAAIIBIIAAAAAAA", "AAAAAAAJJAJJAAAAAAA",
                        "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJFJJAAAAAAA",
                        "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJAJJAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIJBBGGEEEGGBBJIAA", "AAAFAAAAABAAAAAFAAA", "AAAFAAAAAAAAAAAFAAA", "AAAFAAAAABAAAAAFAAA",
                        "BEEJJJBBEGEBBJJJEEB", "CAAAAAAAAFAAAAAAAAC", "CAAAAAAAAFAAAAAAAAC", "CAAAAAAAAFAAAAAAAAC",
                        "BHJIIJBEFIFEBJIIJHB", "AAAAAAKAGIGAKAAAAAA", "AAAAAAKAGIGAKAAAAAA", "AAAAAAKAGIGBKAAAAAA",
                        "AAAAAALLLBLLLAAAAAA", "ABEEIJBBEGEBBJIEEBA", "ACAAAAAAAFAAAAAAACA", "ACAAAAAAAFAAAAAAACA",
                        "ACAAAAAAAFAAAAAAACA", "ABHJJEBJJGJJBEJJHBA", "AAAAAAKAGIGAKAAAAAA", "AAAAAAKAGIGBKAAAAAA",
                        "AAAAAALLLBLLLAAAAAA", "AAABEEJIIGIIJEEBAAA", "AAACAAAAAFAAAAACAAA", "AAACAAAAAFAAAAACAAA",
                        "AAACAAAAAFAAAAACAAA", "AAABJIBBBIBBBIJBAAA", "AAAAAAIIBBBIIAAAAAA", "AAAAAAAJFFFJAAAAAAA",
                        "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA",
                        "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA", "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAFFFAAAAAAAA",
                        "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIJBBGEEEEEGBBJIAA", "AAAJAAAABFBAAAAJAAA", "AAAJAAAAAMAAAAAJAAA", "AAAJAAAABNBAAAAJAAA",
                        "BFFJBBBEGNGEBBBJFFB", "BAAAAAAAFNFAAAAAAAB", "BAAAAAAAFNFAAAAAAAB", "BAAAAAAAFNFAAAAAAAB",
                        "BFFFFJGGINIGGJFFFFB", "AAAAAFAAINIAAFAAAAA", "AAAAAFAAINIAAFAAAAA", "AAAAAFAAINIAAFAAAAA",
                        "AAAAABBBBNBBBBAAAAA", "ABFFIBBEGNGEBBIFFBA", "ABAAAAAAFNFAAAAAABA", "ABAAAAAAFNFAAAAAABA",
                        "ABAAAAAAFNFAAAAAABA", "ABFFFEBJGNGJBEFFFBA", "AAAAAFAAINIAAFAAAAA", "AAAAAFAAINIAAFAAAAA",
                        "AAAAABBBBNBBBBAAAAA", "AAABFFJIGNGIJFFBAAA", "AAABAAAAFNFAAAABAAA", "AAABAAAAFNFAAAABAAA",
                        "AAABAAAAFNFAAAABAAA", "AAABFFFBIIIBFFFBAAA", "AAAAAAABBNBBAAAAAAA", "AAAAAAAAFNFAAAAAAAA",
                        "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAFFNFFAAAAAAA",
                        "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA",
                        "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA",
                        "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA",
                        "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA",
                        "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAFNFAAAAAAAA", "AAAAAAAAANAAAAAAAAA",
                        "AAAAAAAAANAAAAAAAAA")
                .aisle("AAIJBBGGEEEGGBBJIAA", "AAAFAAAAABAAAAAFAAA", "AAAFAAAAAAAAAAAFAAA", "AAAFAAAAABAAAAAFAAA",
                        "BEEJJJBBEGEBBJJJEEB", "CAAAAAAAAFAAAAAAAAC", "CAAAAAAAAFAAAAAAAAC", "CAAAAAAAAFAAAAAAAAC",
                        "BHJIIJBEFIFEBJIIJHB", "AAAAAAKAGIGAKAAAAAA", "AAAAAAKAGIGAKAAAAAA", "AAAAAAKAGIGAKAAAAAA",
                        "AAAAAALLLBLLLAAAAAA", "ABEEIJBBEGEBBJIEEBA", "ACAAAAAAAFAAAAAAACA", "ACAAAAAAAFAAAAAAACA",
                        "ACAAAAAAAFAAAAAAACA", "ABHJJEBJJGJJBEJJHBA", "AAAAAAKAGIGAKAAAAAA", "AAAAAAKAGIGAKAAAAAA",
                        "AAAAAALLLBLLLAAAAAA", "AAABEEJIIGIIJEEBAAA", "AAACAAAAAFAAAAACAAA", "AAACAAAAAFAAAAACAAA",
                        "AAACAAAAAFAAAAACAAA", "AAABJIBBBIBBBIJBAAA", "AAAAAAIIBBBIIAAAAAA", "AAAAAAAJFFFJAAAAAAA",
                        "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA",
                        "AAAAAAAJFFFJAAAAAAA", "AAAAAAAJFFFJAAAAAAA", "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAFFFAAAAAAAA",
                        "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAFFFAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIJBBBGGEGGBBBJIAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "BBEGGJJJBEBJJJGGEBB", "CCAAAAAAAAAAAAAAACC", "CCAAAAAAAAAAAAAAACC", "CCAAAAAAAAAAAAAAACC",
                        "BBHJIIBEEGEEBIIJHBB", "AFAAAAACAAACAAAAAFA", "AFAAAAACAAACAAAAAFA", "AFAAAAACAAACAAAAAFA",
                        "AFAAAAAILBLIAAAAAFA", "ABBEIIJJBEBJJIIEBBA", "ACCAAAAAAAAAAAAACCA", "ACCAAAAAAAAAAAAACCA",
                        "ACCAAAAAAAAAAAAACCA", "ABBHJEIBJJJBIEJHBBA", "AAAFAAACAAACAAAFAAA", "AAAFAAACAAACAAAFAAA",
                        "AAAFAAAILBLIAAAFAAA", "AAABBEJJIIIJJEBBAAA", "AAACCAAAAAAAAACCAAA", "AAACCAAAAAAAAACCAAA",
                        "AAACCAAAAAAAAACCAAA", "AAABBJIBBBBBIJBBAAA", "AAAAAAAIIBIIAAAAAAA", "AAAAAAAJJAJJAAAAAAA",
                        "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJFJJAAAAAAA",
                        "AAAAAAAJJAJJAAAAAAA", "AAAAAAAJJAJJAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIJJBBBGGGBBBJJIAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "ABEEGGJJBBBJJGGEEBA", "ACAAAAAAAAAAAAAAACA", "ACAAAAAAAAAAAAAAACA", "ACAAAAAAAAAAAAAAACA",
                        "ABHHJIIBBGBBIIJHHBA", "AAAAAAAAKAKAAAAAAAA", "AAAAAAAAKAKAAAAAAAA", "AAAAAAAAKAKAAAAAAAA",
                        "AAAAAAAALBLAAAAAAAA", "AABEEIIJBBBJIIEEBAA", "AACAAAAAAAAAAAAACAA", "AACAAAAAAAAAAAAACAA",
                        "AACAAAAAAAAAAAAACAA", "AABHHJIIBBBIIJHHBAA", "AAAAAAAAKAKAAAAAAAA", "AAAAAAAAKAKAAAAAAAA",
                        "AAAAAAAALBLAAAAAAAA", "AAAABEEJJJJJEEBAAAA", "AAAACAAAAAAAAACAAAA", "AAAACAAAAAAAAACAAAA",
                        "AAAACAAAAAAAAACAAAA", "AAAABJJIBFBIJJBAAAA", "AAAAAAAAIAIAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAIIJJBBBBBBBJJIIAA", "AAAAJAAAAAAAAAJAAAA", "AAAAJAAAAAAAAAJAAAA", "AAAAJAAAAAAAAAJAAAA",
                        "ABBEJGGJJBJJGGJEBBA", "AGCAAAAAAAAAAAAACGA", "AGCAAAAAAAAAAAAACGA", "AGCAAAAAAAAAAAAACGA",
                        "ABBHHJIIJJJIIJHHBBA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAABAAAAAAAAA", "AABBEEIIJBJIIEEBBAA", "AAGCAAAAAAAAAAACGAA", "AAGCAAAAAAAAAAACGAA",
                        "AAGCAAAAAAAAAAACGAA", "AABBHHJEEEEEJHHBBAA", "AAAAAAAAAFAAAAAAAAA", "AAAAAAAAAFAAAAAAAAA",
                        "AAAAAAAAABAAAAAAAAA", "AAAABBEEEFEEEBBAAAA", "AAAAGCAAAAAAACGAAAA", "AAAAGCAAAAAAACGAAAA",
                        "AAAAGCAAAAAAACGAAAA", "AAAABBJJIFIJJBBAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAIIJJBBBBBJJIIAAA", "AAAAAJAAAAAAAJAAAAA", "AAAAAJAAAAAAAJAAAAA", "AAAAAJAAAAAAAJAAAAA",
                        "AABBEJGGJBJGGJEBBAA", "AACCAAAAAAAAAAACCAA", "AACCAAAAAAAAAAACCAA", "AACCAAAAAAAAAAACCAA",
                        "AABBHHJIIFIIJHHBBAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAABBEEIIIIIEEBBAAA", "AAACCAAAAAAAAACCAAA", "AAACCAAAAAAAAACCAAA",
                        "AAACCAAAAAAAAACCAAA", "AAABBHHJJFJJHHBBAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAABBBEFEBBBAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA",
                        "AAAAAGCCAAACCGAAAAA", "AAAAABBBJFJBBBAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAIIJJJJJJJIIAAAA", "AAAAAAAAFJFAAAAAAAA", "AAAAAAAAFOFAAAAAAAA", "AAAAAAAAFJFAAAAAAAA",
                        "AAABBEEGJJJGEEBBAAA", "AAAGCAAAAAAAAACGAAA", "AAAGCAAAAAAAAACGAAA", "AAAGCAAAAAAAAACGAAA",
                        "AAABBHHJIFIJHHBBAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAABBEEEFEEEBBAAAA", "AAAACCAAAAAAACCAAAA", "AAAACCAAAAAAACCAAAA",
                        "AAAACCAAAAAAACCAAAA", "AAAABBHHJFJHHBBAAAA", "AAAAAAAFAAAFAAAAAAA", "AAAAAAAFAAAFAAAAAAA",
                        "AAAAAAAFAAAFAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA",
                        "AAAAAAACCBCCAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAIIIIIIIIIAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAABBEEEFEEEBBAAAA", "AAAACCAAAAAAACCAAAA", "AAAACCAAAAAAACCAAAA", "AAAACCAAAAAAACCAAAA",
                        "AAAABBHHJFJHHBBAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAABBBEFEBBBAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA",
                        "AAAAAGCCAAACCGAAAAA", "AAAAABBBHFHBBBAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAABBBEFEBBBAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA", "AAAAAGCCAAACCGAAAAA",
                        "AAAAABBBHFHBBBAAAAA", "AAAAAAAFAAAFAAAAAAA", "AAAAAAAFAAAFAAAAAAA", "AAAAAAAFAAAFAAAAAAA",
                        "AAAAAAAFAAAFAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA",
                        "AAAAAAACCBCCAAAAAAA", "AAAAAAABBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .aisle("AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAABBBBBAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA", "AAAAAAACCBCCAAAAAAA",
                        "AAAAAAABBBBBAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA", "AAAAAAAAAAAAAAAAAAA",
                        "AAAAAAAAAAAAAAAAAAA")
                .where("A", Predicates.any())
                .where("B", blocks(PhoenixTeslaBlocks.ADVANCED_INVARIANT_NAQ_ALLOY_CASING.get()))
                .where("C", blocks(GTBlocks.FUSION_GLASS.get()))
                .where("E", Predicates.lampsByColor(DyeColor.PURPLE))
                .where("F", blocks(ChemicalHelper.getBlock(TagPrefix.frameGt,
                        PhoenixProgressionMaterials.ADVANCED_QUIN_NAQUADIAN_ALLOY)))
                .where("G", Predicates.blocks(PhoenixTeslaBlocks.MACHINE_CASING_RHODIUM_PLATED_PALLADIUM.get()))
                .where("H", Predicates.lampsByColor(DyeColor.BLACK))
                .where("I", blocks(PhoenixTeslaBlocks.ADVANCED_SOURCE_FIBER_CASING.get()))
                .where("J", PhoenixTeslaMachines.hatchPredicate(definition, profile,
                        PhoenixTeslaBlocks.ADVANCED_TESLA_CASING.get()))
                .where("K", blocks(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING.get()))
                .where("L", blocks(PhoenixTeslaBlocks.RELIABLE_NAQUADAH_ALLOY_MACHINE_CASING.get()))
                .where("M", PhoenixPredicates.teslaBatteries(profile.minBatteryTier, profile.maxBatteryTier))
                .where("N", blocks(GTBlocks.COIL_CUPRONICKEL.get()))
                .where("O", controller(blocks(definition.get())))
                .build();
    }
}
